# Dockerfile has been removed.
# For production deployment, you can create your own Dockerfile based on your deployment platform.
# 
# Basic example for reference:
# 
# FROM python:3.11-slim
# WORKDIR /app
# RUN apt-get update && apt-get install -y default-libmysqlclient-dev
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY . .
# RUN python manage.py collectstatic --noinput
# EXPOSE 8000
# CMD ["gunicorn", "agrilink_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
