# Generated by Django 4.2.11 on 2026-04-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=255)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('area_hectares', models.FloatField()),
                ('quantity_planted', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready to Harvest'), ('harvested', 'Harvested')], default='planning', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='core.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_yield', models.FloatField()),
                ('actual_yield', models.FloatField(blank=True, null=True)),
                ('yield_unit', models.CharField(default='kg', max_length=50)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('quality_rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('planting', 'Planting'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('spraying', 'Spraying'), ('weeding', 'Weeding'), ('harvesting', 'Harvesting'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crops.crop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
